apiVersion: v2
name: accounting-api
description: A Helm chart for accounting-api - Accounting Go API
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - accounting
  - api
maintainers:
  - name: accounting-team
home: https://github.com/behrooz/accounting
sources:
  - https://github.com/behrooz/accounting
