{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "accounting-api.fullname" . }}
  labels:
    {{- include "accounting-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_DSN: {{ .Values.secrets.mysqlDsn | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
{{- end }}
